### ISSUE TITLE
ERROR: Dictionary file(s) is missing.

### ISSUE THREAD

**Issue by goldmund256** [velorek1/cwordle#7]
System: Arch Linux 5.16.13-arch1-1
Installed through the [AUR](https://aur.archlinux.org/packages/cwordle-git).

When I launch cwordle, I get the error:
`ERROR: Dictionary file(s) is missing. Create file <dict.txt> and/or <possibles.txt>`

I have to be inside /usr/share/cwordle in order for the play to begin and not see the error.

Given that cwordle seems to install dict.txt and possibles.txt into the dir /usr/share/cwordle by default, could it first look there before complaining it can't find it?

**Comment by velorek1** [comment]
True. I think it's fixed now. Error was due to a previous commit clash. Thank you for letting me know.

**Comment by EysseW** [comment]
I am sorry to report I am still encountering the same issue. Both on the AUR version and when compiling it myself.
EDIT: I doens't work for me when I am in /usr/share/cwordle either.

**Comment by velorek1** [comment]
Yes. For simple use use **cw.c** instead. Try compiling it like this : 
gcc cw.c -o cw 
Run as ./cw
In order to install it with cmake you have to be superuser : 
1) Download or clone repository
2) cd cwordle && cmake . && sudo make install
3) Run as cwordle
